Added json file for 1000 common used igbo words
ijemmao/igbo_api pull request #133
Opened 2020-10-15 02:40 UTC by pappyJ

re

2020-10-15 03:17 UTC, ijemmao requested changes
One last note, you should rename your dictionary from `ig-en_1000_common.json` and place it in the `ig-en` directory instead of placing it inside the `ig-en-1000` directory that you created.

But so far so good!

2020-10-15 03:17 UTC, ijemmao commented on src/dictionaries/parseAndBuild-1000.js
> +const request = require("request");
There's no need to include this script since we aren't going to be running it in the main repo

2020-10-15 03:17 UTC, ijemmao commented on src/config.js
> +const DB_NAME = "igbo_api";
It looks like your text editor changed all the single quotes to double-quotes.

Could you change the double-quotes back to single quotes?

2020-10-15 03:26 UTC, pappyJ commented
Ohhh my ... It's pretier

On Thu, Oct 15, 2020, 4:17 AM Ijemma Onwuzulike <notifications@github.com>
wrote:

> *@ijemmao* requested changes on this pull request.
>
> One last note, you should rename your dictionary from
> ig-en_1000_common.json and place it in the ig-en directory instead of
> placing it inside the ig-en-1000 directory that you created.
>
> But so far so good!
> ------------------------------
>
> In src/dictionaries/parseAndBuild-1000.js
> <https://github.com/ijemmao/igbo_api/pull/133#discussion_r505139529>:
>
> > @@ -0,0 +1,101 @@
> +const request = require("request");
>
> There's no need to include this script since we aren't going to be running
> it in the main repo
> ------------------------------
>
> In src/config.js
> <https://github.com/ijemmao/igbo_api/pull/133#discussion_r505139744>:
>
> > @@ -1,10 +1,13 @@
> -const DB_NAME = 'igbo_api';
> -const TEST_DB_NAME = 'test_igbo_api';
> +const DB_NAME = "igbo_api";
>
> It looks like your text editor changed all the single quotes to
> double-quotes.
>
> Could you change the double-quotes back to single quotes?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ijemmao/igbo_api/pull/133#pullrequestreview-508907857>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APW5Z4CLAT7BOHFBPWQPTK3SKZSUXANCNFSM4SRMEPDQ>
> .
>

2020-10-15 03:49 UTC, pappyJ commented
done.. check again

2020-10-15 04:00 UTC, ijemmao requested changes
It looks like you're still accidentally formatting files.

You could try pulling from `master` and running `yarn install` so that you can use the pre-commit lint check so that it can catch these formatting errors before you make another push!

2020-10-15 04:03 UTC, pappyJ commented on src/server.js
> +  useNewUrlParser: true,
it is caused by prettier ... i'll disable it

2020-10-15 04:17 UTC, pappyJ commented
removed the formatting  , just hope it works this time

2020-10-16 23:15 UTC, ijemmao approved these changes

2020-10-16 23:15 UTC, ijemmao commented
Looks good ✨

2020-10-16 23:15 UTC, merged