Resolves ijemmao/igbo_api#131
ijemmao/igbo_api pull request #180
Opened 2020-10-22 05:45 UTC by oemekaogala

In this patch, I completed two things.

1. the reorganized the documentation comments to align with the corresponding route. This will make it easier for anyone to understand the relationship between the comment/swagger documentation.

2. Added a new route `api/v1/edit/words/:id` to delete a word from mongodb. I also included documentation for this new route.

**Note**: I decided to return the word as a response when it is successfully deleted

2020-10-22 15:26 UTC, ijemmao commented on src/controllers/words.js
> +  const { params: { id } } = req;
There's a chance that a `WordSuggestion` and `GenericWord` document might reference to a `Word` document with either the `originalWordId` or even the `merged` key. I think we should also make a pass through those documents and remove references from those objects.

2020-10-22 15:28 UTC, ijemmao commented on src/routers/router.js
>  const router = express.Router();
It looks like you didn't create an express route for deleting words yet. Inside `editorRouter.js` could you create the delete route like `editorRouter.delete('/words/:id')`?

2020-10-22 15:29 UTC, ijemmao requested changes
This is shaping up! Just a couple things:

* Remove all references to the recently deleted `Word` document inside `WordSuggestion` and `GenericWord` documents
* Create a new express route in `editorRouter` to actually delete a word
* Add Swagger docs to that new route
* Create tests to make sure that not only is the `Word` document actually deleted but there are no more references to that word

2020-10-25 01:40 UTC, oemekaogala commented
Okay thanks for the comments. Will work on this

2020-12-09 01:32 UTC, ijemmao commented
Closing this PR since it's been inactive. Reopen this PR once you are ready for a new review.

2020-12-09 01:32 UTC, closed without merging