refactor(issue-360): used joi to validate developer request body
ijemmao/igbo_api pull request #370
Opened 2021-04-26 00:18 UTC by kenzdozz

solves Issue #360

2021-04-26 16:56 UTC, ijemmao approved these changes
Amazing, the validation file looks so much more cohesive

2021-04-26 17:04 UTC, ijemmao commented on src/middleware/validateDeveloperBody.js
> +    return res.send({ error: validationResult.error.message });
You need to send the status code of  `400`

2021-04-26 17:08 UTC, ijemmao requested changes
Just need to specify the status code

2021-04-27 19:34 UTC, kenzdozz commented
> Just need to specify the status code

Yeah, I missed that. Done now

2021-04-28 01:05 UTC, ijemmao approved these changes

2021-04-28 02:15 UTC, merged